### ISSUE TITLE
Implement personas based filter for listing page

### ISSUE THREAD

**Issue by Simply007** [Kentico/kontent-sample-app-graphql-react#8]
Current GraphQL capabilities allow to filter just by one element value (in this case author). It would be great to showcase multiplier filtering conditions.

Current commented solution is here:
* https://github.com/Kentico/kontent-sample-app-graphql-react/blob/main/src/ListingPage.js

Internal linked: blocked by https://kentico.atlassian.net/browse/DEL-3086

Bonus: 
It would worth a try to add a query for loading all posts but just load persona definition - to list in dropdown only personas that are really used.

**Comment by Simply007** [comment]
@winklertomas - this might be also fairly simple to put pack before release.

**Comment by winklertomas** [comment]
https://github.com/Kentico/kontent-sample-app-graphql-react/pull/22 merged -> closing
